version: '3'
services:
  client:
    image: wfliu66/multi-client
    hostname: client
    mem_limit: 128m

  api:
    image: wfliu66/multi-server
    hostname: api
    mem_limit: 128m

  worker:
    image: wfliu66/multi-worker
    hostname: worker
    mem_limit: 128m

  nginx:
    image: wfliu66/multi-nginx
    hostname: nginx
    mem_limit: 128m
    ports:
      - "80:80"
    links:
      - client
      - server
