version: 2.1
executors:
  default:
    docker:
      - image: circleci/node:14-browsers
  python:
    docker:
      - image: circleci/python:3.7

jobs:
  build:
    executor: default
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.7
          docker_layer_caching: true
      - run:
          name: Build Docker Client Image
          command: docker build -t wfliu66/react-test -f ./client/Dockerfile.dev ./client
      - run:
          name: Run tests
          command: docker run -e CI=true wfliu66/react-test npm run test

      - run:
          name: Build client image after test success
          command: docker build -t wfliu66/multi-client ./client
      
      - run:
          name: Build nginx after test success
          command: docker build -t wfliu66/multi-nginx ./nginx

      - run:
          name: Build server after test success
          command: docker build -t wfliu66/multi-server ./server

      - run:
          name: Build worker after test success
          command: docker build -t wfliu66/multi-worker ./worker

      - run:
          name: log into dockerhub
          command: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
      
      - run:
          name: push images to dockerhub
          command: |
            docker push wfliu66/multi-client
            docker push wfliu66/multi-nginx
            docker push wfliu66/multi-server
            docker push wfliu66/multi-worker

